# 应用名称
server:
  port: 8097




spring:
  mail:
    host: smtp.163.com
    username: xss13523773853@163.com
    password: XGCBQYFHHJQSBCRC
  servlet:
    multipart:
      max-file-size: 8MB
  mvc:
    static-path-pattern: /static/uploads/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cash?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: root


  application:
    name: cashregister
  data:
    redis:
      host: 116.62.53.158
      port: 6379
      database: 0
      password: 1234
      connect-timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 5
          min-idle: 0


#  jpa:
#    hibernate:
#      ddl-auto: update
#      #* create 启动时删数据库中的表，然后创建，退出时不删除数据表
#      #* create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
#      #* update 如果启动时表格式不一致则更新表，原有数据保留
#      #* validate 项目启动表结构进行校验 如果不一致则报错
#    show-sql: true
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    path: log
    name: log/my.log
  level:
    com:
      javaclimb:
        dao: debug
upload:
  path:${user.dir}/uploads/


  #配置mapper xml的路径
#  mybatis-plus.mapper-locations=classpath:com/shang/eduservice/mapper/xml/*.xml


mybatis-plus:
  global-config:
    db-config:
      id-type: auto #id生成规则：数据库id自增
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
#  global-config:
#    db-config:
#      id-type: ASSIGN_ID  #手动赋值
# 外卖项目的图片存放地址
#takeout-food:
#  # 这里目前使用的是是绝对路径
#  images: backend/upload/























#  jpa:
#    hibernate:
#      ddl-auto: create
#
#      #* create 启动时删数据库中的表，然后创建，退出时不删除数据表
#      #* create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错
#      #* update 如果启动时表格式不一致则更新表，原有数据保留
#      #* validate 项目启动表结构进行校验 如果不一致则报错
#    show-sql: true
#
#  redis:
#    port: 6379
#    database: 0
#    password: 1234
#    connect-timeout: 1800000
#    #  spring.redis.lettuce.pool.max-active=20
#    #  #最大阻塞等待时间(负数表示没限制)
#    #  spring.redis.lettuce.pool.max-wait=-1
#    #  #连接池中的最大空闲连接
#    #  spring.redis.lettuce.pool.max-idle=5
#    #  #连接池中的最小空闲连接
#    #  spring.redis.lettuce.pool.min-idle=0
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0